[build]
builder = "NIXPACKS"
buildCommand = "go build -o server cmd/server/main.go && go build -o seed cmd/seed/main.go"

[deploy]
startCommand = "./server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
